version: '3.1'

services:

  jenkinsci:
    build:
      context: ./jenkinsci
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./data/www:/usr/share/nginx/html
      - ./data/letsencrypt/:/etc/letsencrypt/
      - ./data/letsencrypt/acme:/data/letsencrypt/
      - ./data/jenkins:/var/jenkins_home
    env_file: .env
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge