version: '3.1'

services:

  jenkins:
    container_name: 'jenkins'
    image: yorkred/jenkins
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html
      - ./jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge