version: '3.1'

services:

  jenkins:
    container_name: 'jenkins'
    image: yorkred/ngjenkins
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html
      - ./data/nginx/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./data/etc/letsencrypt/live/changemyname/fullchain.pem:/etc/letsencrypt/ssl/fullchain.pem
      - ./data/etc/letsencrypt/live/changemyname/privkey.pem:/etc/letsencrypt/ssl/privkey.pem
      - ./jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge